// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py for languages C and C++
// from https://raw.githubusercontent.com/ForkAwesome/Fork-Awesome/master/src/icons/icons.yml
// for use with https://github.com/ForkAwesome/Fork-Awesome/blob/master/fonts/forkawesome-webfont.ttf

// Modified for use in PS2+:
//   - Restricted glyphs to reduce size

#pragma once

#define ICON_FK_GLYPH_MIN 0xf175
#define ICON_FK_GLYPH_MAX 0xf178
#define ICON_FK_LONG_ARROW_DOWN "\xef\x85\xb5"	// U+f175
#define ICON_FK_LONG_ARROW_UP "\xef\x85\xb6"	// U+f176
#define ICON_FK_LONG_ARROW_LEFT "\xef\x85\xb7"	// U+f177
#define ICON_FK_LONG_ARROW_RIGHT "\xef\x85\xb8"	// U+f178
