#ifndef SHARED_VERSIONS_H
#define SHARED_VERSIONS_H

#include <stddef.h>
#include <stdint.h>

#define STRINGIFY(X) STRINGIFY_(X)
#define STRINGIFY_(X) #X

#ifndef PLATFORM_MICROCONTROLLER
#define PLATFORM_MICROCONTROLLER Unknown
#endif

#define VERSION64(MAJOR, MINOR, PATCH, METADATA) (((uint64_t)MAJOR & 0xFF) << 56) | (((uint64_t)MINOR & 0xFFFF) << 40) | (((uint64_t)PATCH & 0xFFFFFFFF) << 8) | ((uint64_t)METADATA & 0xFF)
#define VERSION_MAJOR(V) ((V >> 56) & 0xFF)
#define VERSION_MINOR(V) ((V >> 40) & 0xFFFF)
#define VERSION_PATCH(V) ((V >> 8) & 0xFFFFFFFF)

#define VERSION_METADATA(V) ((V) & 0xFF)
#define VERSION_METADATA_NONE 0
#define VERSION_METADATA_DEV 1
#define VERSION_METADATA_LATEST 2

#ifndef VERSION_FIRMWARE
#define VERSION_FIRMWARE VERSION64(0, 0, 0, VERSION_METADATA_DEV)
#endif

#ifndef VERSION_CONFIGURATION
#define VERSION_CONFIGURATION 0
#endif

#ifndef VERSION_BOOTLOADER
#define VERSION_BOOTLOADER VERSION64(0, 0, 0, VERSION_METADATA_DEV)
#endif

#ifndef VERSION_MICROCONTROLLER
#define VERSION_MICROCONTROLLER STRINGIFY(PLATFORM_MICROCONTROLLER)
#endif

static const size_t VERSION_MAGIC_BASE = 0xFFFFCC00;
static const size_t VERSION_MAGIC_TOTAL_SIZE = 256;
static const size_t VERSION_MAGIC_OFFSET_FIRMWARE = 0;
static const size_t VERSION_MAGIC_OFFSET_MICROCONTROLLER = VERSION_MAGIC_OFFSET_FIRMWARE + sizeof(uint64_t);
static const size_t VERSION_MAGIC_OFFSET_CONFIGURATION = VERSION_MAGIC_OFFSET_MICROCONTROLLER + sizeof(32);

#endif /* SHARED_VERSIONS_H */