#ifndef SHARED_VERSIONS_H
#define SHARED_VERSIONS_H

#define STRINGIFY(X) STRINGIFY_(X)
#define STRINGIFY_(X) #X

#ifndef PLATFORM_MICROCONTROLLER
#define PLATFORM_MICROCONTROLLER Unknown
#endif

#include <stdint.h>

static const uint16_t VERSION_FIRMWARE = 0xC2FC;
static const char VERSION_MICROCONTROLLER[32] = STRINGIFY(PLATFORM_MICROCONTROLLER);
static const uint16_t VERSION_CONFIGURATION = 0x01;
static const uint16_t VERSION_BOOTLOADER = 0x02;

#endif /* SHARED_VERSIONS_H */