#ifndef SHARED_VERSIONS_H
#define SHARED_VERSIONS_H

#define STRINGIFY(X) STRINGIFY_(X)
#define STRINGIFY_(X) #X

#ifndef PLATFORM_MICROCONTROLLER
#define PLATFORM_MICROCONTROLLER Unknown
#endif

#include <stddef.h>
#include <stdint.h>

static const uint16_t VERSION_FIRMWARE = 0xC2FC;
static const char VERSION_MICROCONTROLLER[32] = STRINGIFY(PLATFORM_MICROCONTROLLER);
static const uint16_t VERSION_CONFIGURATION = 0x01;
static const uint16_t VERSION_BOOTLOADER = 0x02;

static const size_t VERSION_MAGIC_BASE = 0xFFFFCC00;
static const size_t VERSION_MAGIC_TOTAL_SIZE = 256;
static const size_t VERSION_MAGIC_OFFSET_FIRMWARE = 0;
static const size_t VERSION_MAGIC_OFFSET_MICROCONTROLLER = VERSION_MAGIC_OFFSET_FIRMWARE + sizeof(VERSION_FIRMWARE);
static const size_t VERSION_MAGIC_OFFSET_CONFIGURATION = VERSION_MAGIC_OFFSET_MICROCONTROLLER + sizeof(VERSION_MICROCONTROLLER);

#endif /* SHARED_VERSIONS_H */